### ISSUE TITLE
Set off sidebar widgets

### ISSUE THREAD

**Issue by yellowled** [s9y/theme_blog#5]
The sidebar should “set off” from the content a bit more than on the website. Not sure how to do that yet. The Development State should get individual styles.

**Comment by garvinhicking** [comment]
Maybe a dotted line, or a light grey background between sidebar and content

**Comment by yellowled** [comment]
Should be improved/fixed after the cronpull tonight with https://github.com/s9y/website_assets/commit/5ce4811e89a2e176aff46e66d1e4ed2509ba7a56 (border for content) and https://github.com/s9y/website_assets/commit/b3014ecb04c7abfa39bd637fb8ff55e8b7bae4fb (styles for dev state).

@garvinhicking Please close if you think this works (tomorrow).

**Comment by yellowled** [comment]
After 3 months, I'll consider this resolved. ;)
